// mockApplicationsData.js
const mockApplicationsData = [
    {
      id: "1",
      job_id: "job-1",
      candidate_id: "candidate-1",
      name: "John Doe",
      experience: 3,
      education: "Bachelor's Degree in Computer Science",
      skills: ["JavaScript", "React", "CSS"],
      resume: "https://example.com/resume1.pdf",
      status: "applied",
      created_at: "2024-01-01T10:00:00Z",
    },
    {
      id: "2",
      job_id: "job-2",
      candidate_id: "candidate-2",
      name: "Jane Smith",
      experience: 5,
      education: "Master's Degree in Software Engineering",
      skills: ["Python", "Django", "PostgreSQL"],
      resume: "https://example.com/resume2.pdf",
      status: "under review",
      created_at: "2024-01-02T11:00:00Z",
    },
    {
      id: "3",
      job_id: "job-3",
      candidate_id: "candidate-1",
      name: "John Doe",
      experience: 3,
      education: "Bachelor's Degree in Computer Science",
      skills: ["JavaScript", "Node.js", "MongoDB"],
      resume: "https://example.com/resume1.pdf",
      status: "interview scheduled",
      created_at: "2024-01-03T12:00:00Z",
    },
    {
      id: "4",
      job_id: "job-4",
      candidate_id: "candidate-3",
      name: "Emily Davis",
      experience: 2,
      education: "Bachelor's Degree in Information Technology",
      skills: ["Java", "Spring", "MySQL"],
      resume: "https://example.com/resume3.pdf",
      status: "applied",
      created_at: "2024-01-04T13:00:00Z",
    },
    {
      id: "5",
      job_id: "job-5",
      candidate_id: "candidate-2",
      name: "Jane Smith",
      experience: 5,
      education: "Master's Degree in Software Engineering",
      skills: ["Ruby", "Rails", "SQLite"],
      resume: "https://example.com/resume2.pdf",
      status: "rejected",
      created_at: "2024-01-05T14:00:00Z",
    },
  ];
  
  export default mockApplicationsData;
  